# Generated by Django 3.0.5 on 2020-04-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='pincode',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
